### PR TITLE
Patch 0

### PR DESCRIPTION
**Pull request by viridivn**
List of changes:
Add .cartinstall, .dump 3ds, .dump ds
Fix a weird space
Update github url from deleted role to lazr
Fix grammar in .Harold
Has not been tested yet, I'll report back when I have tested.

### CODE REVIEW

**Comment by Lazr1026** [comment]
i think cartinstall is already in there, ig i haven't updated the github but i will add the others

**Comment by viridivn** [comment]
looks like something is broken, don't merge yet

**Comment by viridivn** [comment]
something is very broken here

**Comment by viridivn** [comment]
closing PR because I cannot figure out what is wrong, probably some whitespace thing

**Pull request closed without merging**
