### PR TITLE
Pink screen reassurance

### PR DESCRIPTION
**Pull request by Meganium97**

### CODE REVIEW

**Comment by techmuse8** [comment]
Pink Screen also means messed up file placement as well.

**Comment by Meganium97** [comment]
I will add in that. Thx for letting me know

**Comment by Meganium97** [comment]
Fixed.

**Comment by Meganium97** [comment]
Once again I have edited the file. Instead of cfwinstalled it reads pinkscreen. I think it's ready now.

**Comment by Lazr1026** [comment]
right it looks good

**Comment by Lazr1026** [comment]
oh yeah updating is being a pain

**Pull request merged**
